In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
df = pd.read_csv('data/finaldata.csv')

In [14]:
df.describe()

,id,LATITUDE,LONGITUDE,NDVI,ELEVATION,SLOPE,ASPECT,AWND,TMAX,TMIN,WDF2,WSF2,WILDFIRE,CLASS
count,3.774508e+06,3.774508e+06,3.774508e+06,3.774508e+06,3.774508e+06,3.774508e+06,3.774508e+06,3.774508e+06,3.774508e+06,3.774508e+06,3.774508e+06,3.774508e+06,3.774508e+06,3.774508e+06
mean,7.666877e+05,3.802814e+06,3.881518e+05,1.411918e-01,6.998161e+02,9.096418e+00,1.803474e+02,1.245672e+00,2.223290e+01,6.337382e+00,8.381352e+01,3.341619e+00,1.299870e+01,1.018786e+00
std,4.631489e+05,3.124658e+04,2.829731e+04,7.032619e-02,4.878863e+02,9.002934e+00,1.038366e+02,7.492028e-01,2.522209e+00,3.376416e+00,4.406944e+01,1.388708e+00,1.680937e+02,1.633977e-01
min,1.405000e+03,3.730289e+06,3.205893e+05,-2.419723e-01,-1.500000e+01,0.000000e+00,0.000000e+00,2.165280e-04,1.110137e+01,-7.092472e+00,1.016595e-02,4.997479e-04,0.000000e+00,1.000000e+00
25%,3.627980e+05,3.776999e+06,3.665793e+05,9.283943e-02,2.740000e+02,1.875982e+00,9.018999e+01,8.673849e-01,2.052625e+01,3.994431e+00,5.140021e+01,2.593328e+00,0.000000e+00,1.000000e+00
50%,7.489060e+05,3.803999e+06,3.883593e+05,1.350705e-01,7.320000e+02,4.883108e+00,1.803008e+02,1.032553e+00,2.201429e+01,6.265774e+00,7.322620e+01,3.165060e+00,0.000000e+00,1.000000e+00
75%,1.148820e+06,3.830099e+06,4.112193e+05,1.821155e-01,9.670000e+02,1.487174e+01,2.704607e+02,1.401985e+00,2.450011e+01,9.190248e+00,1.058994e+02,3.856617e+00,0.000000e+00,1.000000e+00
max,1.841586e+06,3.854399e+06,4.404693e+05,7.483355e-01,3.049000e+03,6.595309e+01,3.600000e+02,7.996507e+00,2.829813e+01,1.777958e+01,3.597557e+02,1.339482e+01,5.133226e+03,3.000000e+00

In [15]:
df['CLASS'] = df['CLASS'].astype(int)
df.head()
X_columns = ['LATITUDE', 'LONGITUDE', 'YEAR', 'MONTH', 'NDVI', 'ELEVATION', 'SLOPE', 'TMAX', 'TMIN', 'WDF2', 'WSF2']
y_

,id,LATITUDE,LONGITUDE,DATE,NDVI,ELEVATION,SLOPE,ASPECT,AWND,TMAX,TMIN,WDF2,WSF2,WILDFIRE,CLASS
0,205829,3840629.13,355869.269,2020/02/26,0.306091,1524.0,16.351713,20.611042,2.514588,20.551449,6.028741,46.655315,5.043473,1511.123535,3
1,205830,3840629.13,355959.269,2020/02/26,0.204332,1561.0,24.643478,125.388443,2.495916,20.554436,6.021140,46.492016,5.012155,1580.689087,3
2,205831,3840629.13,356049.269,2020/02/26,0.182950,1601.0,18.099379,311.686859,2.477325,20.557178,6.013507,46.327244,4.980912,1650.681641,3
3,205832,3840629.13,356139.269,2020/02/26,0.134767,1619.0,10.002705,305.491272,2.458813,20.559679,6.005842,46.160988,4.949743,1718.740967,3
4,205833,3840629.13,356229.269,2020/02/26,0.176616,1626.0,10.314038,105.796661,2.440381,20.561935,5.998145,45.993229,4.918644,1783.110962,3